version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: curl ${RENDER_COM_DEPLOY_URL}
workflows:
  test-and-deploy:
    jobs:
      - test-node
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - test-node
